repos:
  # SPELL CHECKER
  - repo: local
    hooks:
      - id: cspell
        name: üìö check spelling of staged files
        entry: bash -c 'npx cspell --no-must-find-files --no-progress --cache --gitignore "**/*.{md,html,tsx,ts,py,yaml,yml}"'
        language: system
        types: [text]
  # PREVENT COMMON GIT/GITHUB ERRORS
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
        name: üëØ check for file name casing conflicts
      - id: check-merge-conflict
        name: üôÖ check for merge conflict markers
      - id: check-added-large-files
        name: üê≥ check for files over 100mb
        args: ["--maxkb=100_000", "--enforce-all"]
  # FORMAT PYTHON WITH BLACK
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: üñ§ python format with black
  # LINT PYTHON WITH PYLINT
  - repo: local
    hooks:
      - id: pylint
        name: üêç python lint with pylint
        entry: pylint
        language: python
        language_version: python3.12
        types: [python]
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
  # LINT/FORMAT JS/TS/JSON WITH BIOME
  - repo: local
    hooks:
      - id: biome-check
        name: üß¨ format with biome
        entry: bash -c 'cd frontend && npm run cleanup'
        language: system
        files: ^frontend/.*\.(js|ts|jsx|tsx|json)$
        pass_filenames: false
  # TYPE CHECK WITH TSC
  - repo: local
    hooks:
      - id: tsc-check
        name: üèÅ TypeScript type check
        entry: tsc --noEmit
        language: system
        types: [ts, tsx]
  # WARN IF TOO MANY FILES IN ONE COMMIT
  - repo: local
    hooks:
      - id: check-file-count
        name: üóÑÔ∏è  check + warn if too many files in commit
        entry: bash -c scripts/.util/warn_many_files_per_commit.sh
        language: system
        types: [text]
        pass_filenames: false
  # LINT DOTENV FILES
  - repo: https://github.com/wemake-services/dotenv-linter
    rev: 0.5.0 # Use the ref you want to point at
    hooks:
      - id: dotenv-linter
        name: ‚úÖ .env lint with dotenv-linter
