name: RUN Python Type Checks
on:
  pull_request:
    branches:
      - main
    paths:
      # only run these tests on pull request if relevant code is changed
      - 'airflow/**'
      - 'data_server/**'
      - 'e2e_tests/**'
      - 'exporter/**'
      - 'python/**'
      - 'run_gcs_to_bq/**'
      - 'run_ingestion/**'
  workflow_dispatch:

jobs:
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: 'pip'

      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      - name: Install mypy
        run: pip install mypy==0.902

      - name: Install mypy dependencies
        run: |
          pip install -r data_server/requirements.txt
          pip install -r run_ingestion/requirements.txt
          pip install -r run_gcs_to_bq/requirements.txt
          pip install -r requirements/tests.txt
          yes | mypy --install-types data_server/ python/data_server/
          yes | mypy --install-types run_ingestion/ python/ingestion/
          yes | mypy --install-types run_gcs_to_bq/ python/ingestion/
          yes | mypy --install-types airflow/dags/

      - name: Run mypy
        run: |
          mypy --config-file=.github/linters/mypy.ini data_server/ python/data_server/
          mypy --config-file=.github/linters/mypy.ini run_ingestion/ python/ingestion/
          mypy --config-file=.github/linters/mypy.ini run_gcs_to_bq/ python/ingestion/
          mypy --config-file=.github/linters/mypy.ini airflow/dags/

