name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'data_server/**'
      - 'python/**'
      - 'exporter/**'
      - 'run_**/**'
      - 'shared_requirements/**'

jobs:
  validate_and_test:
    name: Validate & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install mypy pytest pytest-xdist types-requests types-PyYAML types-setuptools

          pip install -r requirements/tests.txt
          pip install -r data_server/requirements.txt
          pip install -r run_ingestion/requirements.txt
          pip install -r run_gcs_to_bq/requirements.txt
          pip install -r exporter/requirements.txt

          pip install python/ingestion python/data_server python/datasources

      - name: Run Mypy
        run: |
          mypy --install-types --non-interactive \
            --ignore-missing-imports --show-error-codes \
            --config-file=.github/linters/mypy.ini \
            data_server/

          mypy --install-types --non-interactive \
            --ignore-missing-imports --show-error-codes \
            --config-file=.github/linters/mypy.ini \
            python/

          mypy --install-types --non-interactive \
            --ignore-missing-imports --show-error-codes \
            --config-file=.github/linters/mypy.ini \
            run_ingestion/

          mypy --install-types --non-interactive \
            --ignore-missing-imports --show-error-codes \
            --config-file=.github/linters/mypy.ini \
            run_gcs_to_bq/

          mypy --install-types --non-interactive \
            --ignore-missing-imports --show-error-codes \
            --config-file=.github/linters/mypy.ini \
            exporter/

      - name: Run Pytest
        run: |
          pytest \
            python/ \
            data_server/ \
            exporter/ \
            run_gcs_to_bq/ \
            run_ingestion/