name: RUN Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      # only run these tests on pull request if relevant code is changed
      - 'airflow/**'
      - 'data_server/**'
      - 'e2e_tests/**'
      - 'exporter/**'
      - 'python/**'
      - 'run_gcs_to_bq/**'
      - 'run_ingestion/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AHR_API_KEY: 'TGSG5RI-3Z5U6JQ-SFBSMKA-6JPIG3A'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install pytest
          pip install -r requirements/tests.txt
          pip install python/ingestion python/data_server python/datasources

      - name: Verify AHR_API_KEY is set
        run: echo "AHR_API_KEY is set to $AHR_API_KEY"

      - name: Run pytest tests in python/ directory
        run: pytest python/

      - name: Run pytest tests in data_server/ directory
        run: |
          pip install -r data_server/requirements.txt
          pytest data_server/

      - name: Run pytest tests in exporter directory
        run: |
          pip install -r exporter/requirements.txt
          pytest exporter/

      - name: Run pytest tests in run_gcs_to_bq directory
        run: |
          pip install -r run_gcs_to_bq/requirements.txt
          pytest run_gcs_to_bq/

      - name: Run pytest tests in run_ingestion directory
        run: |
          pip install -r run_ingestion/requirements.txt
          pytest run_ingestion/

