name: SuperLinter
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
        # Lint changed files of these langauges using Super Linter shared action
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_DOCKERFILE: true
          VALIDATE_JSON: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          PYTHON_BLACK_CONFIG_FILE: black.ini
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_TERRAFORM_FMT: true
<<<<<<< HEAD
<<<<<<< HEAD
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ENV: true
=======
          VALIDATE_MARKDOWN: true
=======
>>>>>>> 733d46b2 (BACKEND: Split hiv into `_historical` and `_current` (#2362))
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_ENV: true
          VALIDATE_CSS: true
>>>>>>> f0fdfeec (Adjust Super Linter Settings (#2371))
          VALIDATE_BASH: true
          VALIDATE_YAML: true
